modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="enchantmod"
version="1.0.0"
displayName="Enchant Mod"
description='''
Adds Blast Shot and Blood Leech enchantments.
'''

[[dependencies.enchantmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enchantmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
